#ifndef CONFIG_H
#define CONFIG_H

#include "i2c.h"
#include "rtos_libs.h"

#define configSUPPORT_STATIC_ALLOCATION 1

#define LOG_LIBS_PRINT_CUSTOM
#define LOG_LIBS_PRINT_UART
#define LOG_LIBS_USE_PRINTF 2

#define SYSTEM_LED_BLINK_PEROD 500 // ms
#define READ_COMMAND_BUF_LEN 200
#define LOG_LIBS_PRINT_LEN 1000
#define LOG_LIBS_TX_BUFFER_SIZE 0x400
#define LOG_LIBS_RX_BUFFER_SIZE 0x400

#define CDC_TRANSMIT_ATTEMPTS 1000

#define I2C_INSTANSE (hi2c1)
#define I2C_MAX_DATA_SIZE 0xff

#define APP_TASK_STACK_SIZE (1024)      // in dword
#define CLI_READ_TASK_STACK_SIZE (1024) // in dword
#define DISPLAY_TASK_STACK_SIZE (1024) // in dword

#define APP_TASK_PRIORITY (FRTOS_PRIORITY_3)
#define CLI_READ_TASK_PRIORITY (FRTOS_PRIORITY_1)
#define DISPLAY_TASK_PRIORITY (FRTOS_PRIORITY_1)

#define PID_POLLING_PERIOD (10)

#define LV_TICK_PERIOD  (5)
#define LV_TIMER_HANDLER_PERIOD  (10)
// #define DISP_HOR_RES    (128)
// #define DISP_VER_RES    (64)
#endif // !CONFIG_H